[package]
name = "rust-braacket-colley"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
futures = "0.3.31"
reqwest = "0.12.22"
scraper = "0.23.1"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
