[package]
name = "rust-braacket-colley"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rayon = "1.10.0"
regex = "1.11.1"
reqwest = "0.12.22"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread", "macros"] }
